### ISSUE TITLE
Support for Symfony 4

### ISSUE THREAD

**Issue by pscheit** [trappar/AliceGeneratorBundle#6]
Please support Symfony 4 - flex support is optional

**Comment by trappar** [comment]
I looked into this a couple of days ago, but I didn’t get very far with it. I also haven’t yet looked into Alice 3.X to see how much must be changed. I’m not sure I really have the time to be working on this library at the moment, but I would definitely like to get it up and running for Symfony 4. I don’t think anything would even be required for flex support, since all configuration of this bundle is optional.

If you feel like working on it, that would be great. Otherwise I will get to it sooner or later.

**Comment by trappar** [comment]
Release [2.0.0](https://github.com/trappar/AliceGeneratorBundle/releases/tag/v2.0.0) should fix this. Thank you for your patience.

**Comment by pierre-moire** [comment]
Hi, I have errors with Symfony 4 : 

![image](https://user-images.githubusercontent.com/2143238/44538777-ab450300-a702-11e8-85bc-0814649848c0.png)

I am using : 
- Symfony 4.1.1
- PHP 7.2.6
- AliceGeneratorBundle 2.0.0

I tried to fix it but could not achieve it yet.

**Comment by pierre-moire** [comment]
Finally, seems working by turning :

    trappar_alice_generator.metadata.chain_driver:
        public: false
        class: Metadata\Driver\DriverChain
        arguments:
            - ['@Trappar\AliceGenerator\Metadata\Driver\YamlDriver', '@Trappar\AliceGenerator\Metadata\Driver\AnnotationDriver']

into 

    trappar_alice_generator.metadata.chain_driver:
        public: true
        class: Metadata\Driver\DriverChain
        arguments:
            - ['@Trappar\AliceGenerator\Metadata\Driver\YamlDriver', '@Trappar\AliceGenerator\Metadata\Driver\AnnotationDriver']
 
in src/Trappar/AliceGeneratorBundle/Resources/config/services.yml
